version: "3.1"
services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    container_name: rasa-prod
    restart: unless-stopped 